# Generated by Django 5.2.7 on 2026-01-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text="Font Awesome (e.g., 'fas fa-laptop') OR Google Material Icons (e.g., 'material-icons computer')", max_length=100),
        ),
    ]
